# 端口号，项目上下文路径
server:
  port: 8081
  servlet:
    context-path: /yjxms

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/yjxms?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: woshiroot
      validation-query: select 1

  # freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8

  # 启动热部署
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java

  redis:
    host: localhost
    port: 6379
    password: woshimima
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        min-idle: 5
        max-idle: 200
    sentinel:
      master: mymaster
      nodes: localhost:26379, localhost:26380, localhost:26381

# Mybatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.yjxxt.bean;com.yjxxt.query;com.yjxxt.dto
  configuration:
    map-underscore-to-camel-case: true

# pageHelper
pagehelper:
  helper-dialect: mysql

# 设置日志级别
logging:
  level:
    com:
      yjxxt:
        mapper: debug
